# Generated by Django 4.1.2 on 2022-10-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField(verbose_name='Номер телефона')),
                ('mobile_operator_code', models.IntegerField(verbose_name='Код мобильного оператора')),
                ('tag', models.TextField(verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Текст сообщения для доставки клиенту')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время запуска')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время окончании')),
                ('client_filter', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='mailing.client', verbose_name='id клиента')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_messages', to='mailing.mailing', verbose_name='id рассылки')),
            ],
        ),
    ]
