# Generated by Django 4.1.2 on 2022-10-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_client_options_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing',
            name='client_sex_filter',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1),
        ),
    ]
