# Generated by Django 4.1.2 on 2022-10-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_client_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
    ]
