version: '3'

services:
  mailing:
    container_name: mailing_conteiner
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
      - celery
  celery:
    container_name: celery_mailing
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_celery
    volumes:
      - .:/code
    command: [ 'celery', '-A', 'config.celeryapp',  'worker', '-l', 'info' ]
    depends_on:
      - redis

  db:
    image: postgres:14-alpine
    container_name: mailing_db_conteiner
    environment:
      - POSTGRES_DB=mailing_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    hostname: redis

volumes:
  pg_data:

